version: '3.8'

services:
  eVoteProjectUsers:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eVoteProjectUsers
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5435:5432
    volumes:
      - pg1:/var/lib/postgresql/data

  eVoteProjectVotes:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eVoteProjectVotes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5436:5432
    volumes:
      - pg2:/var/lib/postgresql/data

volumes:
  pg1:
  pg2:
