name: eVote CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Start Docker containers with docker-compose
      run: docker-compose up -d
      working-directory: docker

    - name: Build backend with Maven
      run: mvn clean install --file backend/pom.xml
    
    - name: Run tests for backend
      run: mvn test --file backend/pom.xml
      
    - name: Install dependencies for frontend
      run: npm install
      working-directory: frontend 
    - name: Run tests for frontend
      run: npm test
      working-directory: frontend
      
    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Stop Docker containers with docker-compose
      run: docker-compose down
      working-directory: docker
